### ISSUE TITLE
Format month calendar like TailwindUI example

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#1]
On page https://tailwindui.com/components/application-ui/data-display/calendars, the example titled "Month view"

**Comment by dev-charles15531** [comment]
Hello Kyle!
Would you want the modal to be available?
From what i see on the TailwindUI, there's no modal. And on md screens downwards, events get listed below the calendar onclicking on any calendar day box

**Comment by paradigmventures** [comment]
Yes, I want a modal overlay to display event details when a user clicks on an event listing in the month view. Unfortunately, the Tailwind UI examples didn't build any modal overlays. 

Proton Calendar has a nice month view UI with modal overlay for event details.  Attaching a screenshot to provide another example:

<img width="1185" alt="Screen Shot 2023-02-09 at 3 19 19 AM" src="https://user-images.githubusercontent.com/124636541/217786924-941fee05-e3c3-4e12-ab42-73268ad513f2.png">

For md screens and smaller, we can exclude the section below the month view which lists event details. I'm primarily interested in the month view.

**Comment by dev-charles15531** [comment]
Alright!
Would get that done

**Comment by dev-charles15531** [comment]
But in my earlier question, i wasn't talking about the single event details modal.

On my calendar:
Desktop screens: Each grid box displays a maximum of 3 events  and a clickable text below showing the number of event(s) left to view. Onclicking on that text, a modal appears listing all events available on that day.
Mobile screens: Each grid box displays the number of event(s) available for that day, and on clicking on the grid, a modal appears listing all events available on that day.


TailwindUI:
Desktop screens: Each grid box displays a maximum of 3 events  and a clickable text below showing the number of event(s) left to view. Onclicking on that text, no modal appears, instead, all events for that day are listed below the calendar.
Mobile screens: Each grid box displays the number of event(s) available for that day represented in small circles, and on clicking on the grid, no modal appears, instead, all events for that day are listed below the calendar.


The screenshot attached shows the modal i'm talking about on my projects calendar 

![ss2.png](https://user-images.githubusercontent.com/68998548/217802559-4883a7b3-2dae-40bb-baf7-eb4a7ce492aa.png)

![ss5.png](https://user-images.githubusercontent.com/68998548/217802592-2e3016ce-ff50-44b4-8b4a-6f5e1dfdc2bb.png)

**Comment by paradigmventures** [comment]
I see. Yes, let's implement the EventListModal. (I've added more than 3 events to a day to see the overflow case in action here)

I checked Proton Calendar and took a screenshot of how they designed the modal, attached:

<img width="1186" alt="Screen Shot 2023-02-09 at 1 48 41 PM" src="https://user-images.githubusercontent.com/124636541/217936078-d9da7f5d-4cc8-4dfa-b866-96ec94a96391.png">

As far as modal UI design, let's keep it small and near the day's grid box, rather than maximizing the modal to the window size (for desktop screens). Same for mobile screens: overlay as modal, not list below like TailwindUI is doing.

Also, in code, let's abstract out EventListModal and EventDetailModal into component files, if possible.

**Comment by dev-charles15531** [comment]
Alright then..

Was about pushing the new UI (without modal) and some features i've worked on now, but i guess i'll have to work on the event list modal now

**Comment by paradigmventures** [comment]
@dev-charles15531 Got your code merged, built, & published to dev1. Excellent work!

Can you add styling to the month view so that it vertically expands to fill the available window space?

**Comment by dev-charles15531** [comment]
On mobile or desktop?

**Comment by paradigmventures** [comment]
Desktop
