### ISSUE TITLE
Global UI Refactor

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#11]
I want to reproduce the Google Calendar UI more closely: fixed top navbar, sliding sidebar underneath for calendars, maximized monthly calendar view to fill screen.

Top Navbar (left justified buttons)
- Three stacked lines button opening/closing the sidebar
- "My Cal" brand text
- Three-in-One monthly calendar navigation buttons [previous month "<", "Today", next month ">"]
- Text indicating which month is actively being viewed "February 2023"

Top Navbar (right justified button)
- "Add Event" button, to the left of the User menu avatar img
- User menu with single option to "Log Out"

Sidebar
- Begins below the top navbar (not overlapping to top of screen), extends to the bottom of the screen, fixed to left side of screen
- No Tailwind UI indigo logo
- Has "Add Calendar" button instead of "Dashboard" menu (styling similar to "Add Event" button)
- Calendar list remains collapsable within a menu item (only Calendar list is within a collapsable menu, "Add" button above is separate)
- Any vertical overflow from the calendar list scrolls within the sidebar

Month Calendar View
- Remove padding (p-6) so that monthly calendar fills up to the top navbar, left to the sidebar, right to the edge of the screen, bottom to the edge of the screen
- Collapsing the sidebar will expand the monthly calendar view to the left edge of the screen
- No "Top" component for the monthly calendar view, as the buttons have moved to the main navbar (the remaining dropdown calendar widget can be discarded)

**Comment by dev-charles15531** [comment]
Alright.
I would read carefully to understand the concept and write back.

**Comment by dev-charles15531** [comment]
On google calendar, clicking on the current month ie: "March 2023" drops down the calendar widget you're asking to be discarded.
This drop down only happens when the calendar is fully maximixed.

Do you still want this widget discarded?

**Comment by paradigmventures** [comment]
On second thought, let's keep the dropdown widget. It does has a use case of jumping through years, rather than stepping through each month.

For the display:
- No calendar icon on left
- "March 2023" in styling we already have (bold)
- down chevron icon to the right (like google calendar)
- similar border-radius rounding of corners, like the three-in-one nav widget

Both the three-in-one nav widget and the dropdown widget will be buttons with white-bg on top navbar white-bg (where the buttons are currently accented on a light-grey-bg), let's see how that looks

**Comment by dev-charles15531** [comment]
Alright, noted!

**Comment by paradigmventures** [comment]
For the sidebar opening/closing, please add a slight transition, and also no hovering interaction when closed. Let the hamburger icon button in the top navbar be the sole control for opening/closing. Don't need to display any sidebar icons when closed. (I like this UX in Google Calendar)

**Comment by paradigmventures** [comment]
Please also format the calendar dropdown widget similarly to this Tailwind UI example:
https://tailwindui.com/components/application-ui/data-display/calendars#component-c6e8b2bf7f65e8987b7012d3bbe5caf1
<img width="350" alt="Screen Shot 2023-03-02 at 4 03 31 PM" src="https://user-images.githubusercontent.com/124636541/222580457-b6eae4f7-6fb9-495f-9caf-e87e87f25e5c.png">
