### ISSUE TITLE
Event Detail popover buttons

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#13]
When the Event Detail popover is opened, please add two additional buttons next to the "X" close button: Edit, and Delete
-The Edit button should render with a "pencil" icon
-The Delete button should render with a "trash can" icon

The Edit button should close the Edit Detail popover and open up the Edit Detail modal with an editable form for the event.

The Delete button should ask the user to confirm, delete the event, and refresh the event data accordingly.

**Comment by dev-charles15531** [comment]
what are the API endpoints to handle the edit and delete

**Comment by paradigmventures** [comment]
The API endpoint for editing and deleting an event is the same URL with different HTTP verbs (PUT & DELETE):

`PUT /api/event/<EVENT-UUID>`
`DELETE /api/event/<EVENT-UUID>`

So for example:
`DELETE /api/event/dac28bde-425b-4283-8fb9-e021ebbc565b`

The event-uuid field should be present in the context of the Event Detail popover, and can be passed as a parameter to an event-detail.js store, as an example implementation

**Comment by paradigmventures** [comment]
Also, the PUT and DELETE requests will have to include the csrf header, like the POST request, so the backend can authenticate the request:
`headers: { "X-CSRFToken": this.$cookies.get("csrftoken"), },`
