### ISSUE TITLE
Event data field change (start and end dates)

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#14]
Instead of an Event model containing the fields 'start_dt' and 'end_dt', I've looked at how Google Calendar stores data and decided to split the fields into DateFields and DatetimeFields, with an additional is_all_day field to know which field to grab data from.  So now an Event has the following fields:

- start_date (DateField: YYYY-MM-DD)
- start_datetime (DatetimeField: To Be Implemented)
- end_date
- end_datetime
- is_all_day (BooleanField)

Please update the client GET and POST for Events to reflect `start_date` and `end_date`

**Comment by dev-charles15531** [comment]
Alright, would do that now
