### ISSUE TITLE
Events data access refactoring

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#15]
I've refactored and extended the Events api endpoint. Now it handles a list of calendar slugs, as well as start and end dates, to filter data on.  Instead of accessing Event data for a given user for all time, I'd like to access Event data for the active month, with an additional list of the selected calendars.

Depending on how UI/UX performance degrades when accumulating data over the months, either we save data locally and let it accumulate while navigating months, or drop inactive month data while refreshing a new month (previous/next).  As an aside, I've imported google calendar data locally that goes back many years, which amounts to a couple MBs, and creates considerable UI/UX lag in navigating through the months.

API endpoint params example:
`/api/events?start_date=2023-03-01&end_date=2023-03-31&calendars=personal,supplements,meditation`

The `start_date` should be the first day of the active month.
The `end_date` should be the last day of the active month.
The `calendars` parameter should be a comma-delimited list of the UI selected calendars, as a string.

**Comment by dev-charles15531** [comment]
Okay, noted.
I'll have to refactor

**Comment by dev-charles15531** [comment]
i think i'll need the instructions to use your dev server now, so i can see how the data from the above API call is returned/formatted.

**Comment by paradigmventures** [comment]
Here is an example copy/paste to show the json output (events that are within the date range and that are associated with any of the calendars given are returned in a flat list of objects):
```
[
    {
        "calendar": "personal",
        "calendars": null,
        "uuid": "2362755b-17b4-49fb-81c6-e80111cdcbdb",
        "title": "Event One",
        "is_all_day": true,
        "start_date": "2023-03-04",
        "start_datetime": null,
        "end_date": "2023-03-05",
        "end_datetime": null,
        "description": ""
    },
    {
        "calendar": "personal",
        "calendars": null,
        "uuid": "1958a763-24fe-47ea-b9f1-f16a91a7ba22",
        "title": "Event Two",
        "is_all_day": true,
        "start_date": "2023-03-05",
        "start_datetime": null,
        "end_date": "2023-03-06",
        "end_datetime": null,
        "description": ""
    },
    {
        "calendar": "supplements",
        "calendars": null,
        "uuid": "7c0ff783-f3c7-40b0-8b1f-64c7936dc1bd",
        "title": "Event Three",
        "is_all_day": true,
        "start_date": "2023-03-09",
        "start_datetime": null,
        "end_date": "2023-03-10",
        "end_datetime": null,
        "description": "asd"
    }
]
```

I will write up the integrated dev server instructions and email them over to you when they're ready

**Comment by dev-charles15531** [comment]
Alright.

**Comment by paradigmventures** [comment]
> i think i'll need the instructions on how to use your dev server now, so i can see how the data from the above API call is returned/formatted.

Instructions are now available here:
https://github.com/paradigmventures/mycal-server/blob/main/README.md

Let me know if you have any questions or run into any issues getting setup.
