### ISSUE TITLE
Add Event Form

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#17]
Can you change the AddEventForm field for `state_date` and `end_date` so that it only POSTs data in the format `YYYY-MM-DD`?  (No time needed)

Also, can you use similar dropdown styling for the `calendar` dropdown, like in AddCalendar Color?  So for example, the `calendar` dropdown listing would have a color circle to the left of the calendar name, on a white background with a checkmark on the right indicated which option is selected

**Comment by dev-charles15531** [comment]
Alright, i would.
