### ISSUE TITLE
Form defaults

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#22]
For the AddEventForm, please set the initial focus on the "title" input field, instead of the close modal button.  Same with the AddCalendarForm, set focus to "title".

Also, for the AddEventForm, please set default values for "start date" and "end date" to be the current day.

For md & lg screens, can you combine the date fields onto a single form line, where they split width 50/50?

**Comment by dev-charles15531** [comment]
Yes, i can.
i would do that.
