### ISSUE TITLE
Add New Event modal

### ISSUE THREAD

**Issue by paradigmventures** [paradigmventures/mycal-client#5]
Need a [+] button in the UI which opens up a modal overlay with a form to add a new event.  Submitting the form should send a POST request to the API with the Event data. The Event should render in the month calendar when the modal overlay closes.

API endpoint to Create Event:
POST https://dev1.my-cal.io/api/events

**Comment by paradigmventures** [comment]
Let's keep the "Add event" text button, and make it open a NewEventModal with a form to accept event details, centered on the screen.

**Comment by dev-charles15531** [comment]
Okay great!
